# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('D', 'DONE'), ('P', 'PENDING'), ('M', 'MISSED')], default='P', max_length=1),
        ),
    ]
